### ISSUE TITLE
请问这个推送功能在iOS上也是可用的吗

### ISSUE THREAD

**Issue by Orenoid** [kooritea/mpush-pwa-client#4]
最近打算基于pwa写一个类似的工具，但是我查了下发现iOS好像不支持web本地通知，想请问下这个通用客户端在iOS端也实测可用吗？谢谢！

**Comment by kooritea** [comment]
ios不支持fcm
只能一直存在后台用websocket(不推荐，耗电)

**Comment by Orenoid** [comment]
不好意思，刚看到，多谢回复。
我倒不太介意电量问题，就是想确认下这个通用pwa客户端在iOS系统有实际推送成功过吗？因为根据我在网上查的方案，普遍说法都是iOS还不支持web通知，如果可行的话，我就按照大佬这个客户端去实现了，谢谢。

**Comment by kooritea** [comment]
我没有ios设备所以我也不知道ios的pwa是什么情况…

**Comment by Orenoid** [comment]
> 我没有ios设备所以我也不知道ios的pwa是什么情况…

好的，依旧感谢。
